CREATE TABLE IF NOT EXISTS HELIOS_USER(
    ID serial PRIMARY KEY ,
    SUBJECT VARCHAR(255) not null UNIQUE,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    BIRTHDATE DATE);

CREATE TABLE IF NOT EXISTS  HELIOS_ADDRESS(
    ID bigserial PRIMARY KEY,
    HELIOS_USER_ID INTEGER not null references HELIOS_USER(ID),
    ADDRESS Text not null,
    ADDRESS_COMPLEMENT Text,
    ZIP_CODE VARCHAR(6) not null,
    CITY VARCHAR(255) not null,
    COUNTRY VARCHAR(255) not null
)